# 20210319
# 配置文件
# v1.0
# 用于进行项目分析配置

######## 项目基本信息 #########
project: "Chem"                                                 # 定义项目
rawdata: "/home/bioinfo/ubuntu/project/Test_20210319/rawdata"   # 原始数据存放文件夹
output: "/home/bioinfo/ubuntu/project/Test_20210319/output"     # 结果输出文件夹
sample:                                          # 样本编号
pair:                                                           # 配对样本编号，当填写时，使用配对样本分析模式(程序未完成)

####### 临床/收样信息 #########
clinical:
  sampleID: 
  name: 
  gender: 
  age: 
  send: 
  office: 
  doctor: 
  type: 
  diagnosis: 
  orign_id: 
  collect_date: 
  p_id: 
  report_date: 

######## 项目运行参数 ##########
process:                                               # 流程设定值，不运行则不填写
  threads: 8                                           # 流程运行线程数
  QC:  "fastp"                                                # QC程序
  Mapping:  "bwa_mem"                                           # 比对程序
  Mutation:                                            # 分析流程
    SNV_indel:  "gatk_m2"                                       # 变异检测
    CNV:                                               # CNV检测
    SV:  "manta"                                       # SV检测
  Annotation: "annovar"                                # 注释
  Other:                                               # 其他分析项目
    HLA:                                               # HLA分型分析
    MSI:                                               # MSI分析
    TMB:                                               # TMB分析
  Report: true                                        # 是否生成报告


########## 模块设定 ###########
setting:
  QC:
    UMI_loc: 
    UMI_len: 
    UMI_structure:
  Mapping:
    databases: "/home/bioinfo/ubuntu/database/hg19"
    reference: "/home/bioinfo/ubuntu/database/hg19/ucsc.hg19.fasta"
    markDups: true
    removeDups: false
    recalibrate: true
    mills: "Mills_and_1000G_gold_standard.indels.hg19.sites.vcf"
    indel_1000g: "1000G_phase1.indels.hg19.sites.vcf"
    snp_1000g: "dbsnp_138.hg19.vcf"
  Mutation:
    pon:
    gatk_filter:
      run: false                                       # 是否进行mutect2结果的过滤，注意，运行此步必须有bed文件
      small_exac: "small_exac_common_3_hg19.vcf"
    filter:
      DP: 1000
      QUAL: 20
      MAF: 0.01
    Bed: "/home/bioinfo/ubuntu/database/hg19/cnv/tmerge.bed"
    CNV:
      target: "/home/bioinfo/ubuntu/database/hg19/cnv/t.target.bed"
      antitarget: "/home/bioinfo/ubuntu/database/hg19/cnv/t.antitarget.bed"
      baseline: "/home/bioinfo/ubuntu/database/hg19/cnv/reference.t.cnn"
    gnomad: "af-only-gnomad.raw.sites.hg19.vcf.gz"
  Annotation:
    humandb: "/home/bioinfo/ubuntu/database/humandb"
    buildver: "hg19"
    refFlat: "/home/bioinfo/ubuntu/database/hg19/hg19_refFlat.txt"
  Other:
    msisensor2_model: "/home/bioinfo/ubuntu/software/msisensor2/models_hg19_GRCh37"
    msisensorpro_baseline: "/home/bioinfo/ubuntu/project/MSI_20210305/Config/msi_pro_recal/hg19.msi.list_baseline"
    msi_list: "/home/bioinfo/ubuntu/database/hg19/hg19.msi.list"
    PanelSize:
  Report:
  REMOVE_TMP: false
