# 20210222
# NCCL项目标准化配置文件
# NCCL过滤深度设定为500X，突变丰度为0.02

######## 项目基本信息 #########
project: "LungYT"                                                 # 定义项目
rawdata: "/home/bioinfo/ubuntu/project/LungYT_20210225/Rawdata"   # 原始数据存放文件夹
output: "/home/bioinfo/ubuntu/project/LungYT_20210225/Output"     # 结果输出文件夹
sample: "test"                                          # 样本编号
pair:                                                             # 配对样本编号，当填写时，使用配对样本分析模式(程序未完成)


######## 项目运行参数 ##########
process:                                               # 流程设定值，不运行则不填写
  threads: 8                                           # 流程运行线程数
  QC: "fastp"                                          # QC程序
  Mapping:   "bwa_mem"                                 # 比对程序
  Mutation:                                            # 分析流程
    SNV_indel: "gatk_m2"                               # 变异检测
    CNV: "cnvkit"                                      # CNV检测
    SV: "lumpy"                                        # SV检测
  Annotation:  "annovar"                               # 注释
  Other:                                               # 其他分析项目
    HLA:                                               # HLA分型分析
    MSI:                                               # MSI分析
    TMB:                                               # TMB分析
  Report: false                                        # 是否生成报告


########## 模块设定 ###########
setting:
  QC:
    UMI_loc: "per_read"
    UMI_len: "4"
    UMI_structure:
  Mapping:
    databases: "/home/bioinfo/ubuntu/database/hg19"
    reference: "/home/bioinfo/ubuntu/database/hg19/ucsc.hg19.fasta"
    markDups: false
    removeDups: false
    recalibrate: true
    mills: "Mills_and_1000G_gold_standard.indels.hg19.sites.vcf"
    indel_1000g: "1000G_phase1.indels.hg19.sites.vcf"
    snp_1000g: "1000G_phase1.snps.high_confidence.hg19.sites.vcf"
  Mutation:
    pon:
    gatk_filter:
      run: false                                             # 是否进行mutect2结果的过滤，注意，运行此步必须有bed文件
      small_exac: "small_exac_common_3_hg19.vcf"
    filter:
      DP: 2000
      QUAL: 20
      MAF: 0.001
    Bed: 
    CNN: "/home/bioinfo/ubuntu/project/NCCL/cnv/normal.cnn"
    gnomad: "af-only-gnomad.raw.sites.hg19.vcf.gz"
  Annotation:
    humandb: "/home/bioinfo/ubuntu/database/humandb"
    buildver: "hg19"
  Other:
  Report:
  REMOVE_TMP: false
